# Generated by Django 5.2.3 on 2025-06-26 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FacutlyModel',
            new_name='FacultyModel',
        ),
    ]
